### ISSUE TITLE
Opening file comparison causes Tabnine to throw exception, prevents comparison tab from opening

### ISSUE THREAD

**Issue by GamesmenJordan** [codota/tabnine-intellij#160]
When attempting to open a "Compare" tab, Tabnine errors out in the background and prevents the comparison tab from displaying.

If it is important, the file being compared to is outside of the project directory, the files are both PHP files, the smaller file is around 61kB and the larger file is around 330kB.

Output from `idea.log`:
```
2021-06-15 10:06:18,158 [420460416]   WARN - BinaryProcessRequesterProvider - Tabnine is in invalid state, it is being restarted. 
com.tabnine.binary.exceptions.TabNineDeadException: Binary is dead
	at com.tabnine.binary.BinaryProcessRequesterImpl.request(BinaryProcessRequesterImpl.java:36)
	at com.tabnine.binary.BinaryRequestFacade.lambda$executeRequest$0(BinaryRequestFacade.java:31)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-15 10:06:18,192 [420460450]   WARN - ine.binary.BinaryRequestFacade - Tabnine's threw an unknown error during request. 
java.util.concurrent.ExecutionException: com.tabnine.binary.exceptions.TabNineDeadException: Binary is dead
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:32)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.lifecycle.BinaryStateService.updateState(BinaryStateService.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.tabnine.binary.exceptions.TabNineDeadException: Binary is dead
	at com.tabnine.binary.BinaryProcessRequesterImpl.request(BinaryProcessRequesterImpl.java:36)
	at com.tabnine.binary.BinaryRequestFacade.lambda$executeRequest$0(BinaryRequestFacade.java:31)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 7 more
```

gz#1764

**Comment by maya-tabnine** [comment]
What version of Tabnine plugin and engine do you use?
Please attach your config file, open the Tabnine Hub (click the Tabnine icon in IDE's status bar) and scroll down to "Config file path".

**Comment by GamesmenJordan** [comment]
It turns out the issue was caused by another plugin, the Tabnine crash was a symptom rather than the cause.
