### ISSUE TITLE
Do not put promotions in the status bar

### ISSUE THREAD

**Issue by fcFn** [codota/tabnine-intellij#236]
The status bar is never a place for promotions. 

Also this promotion is causing recurring IDE errors: 

```
com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=[REDACTED], containerState=DISPOSE_COMPLETED, 
componentStore=[REDACTED]) (disposed) (class com.intellij.openapi.project.impl.ProjectExImpl) has already been disposed 
(see the cause for stacktrace) so the child: com.tabnine.statusBar.StatusBarPromotionWidget@7ba30f44 (class com.tabnine.statusBar.StatusBarPromotionWidget) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.openapi.wm.impl.status.EditorBasedWidget.<init>(EditorBasedWidget.java:37)
	at com.tabnine.statusBar.StatusBarPromotionWidget.<init>(StatusBarPromotionWidget.java:32)
	at com.tabnine.statusBar.StatusBarPromotionProvider.getWidget(StatusBarPromotionProvider.java:21)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetProviderToFactoryAdapter.getWidget(StatusBarWidgetProviderToFactoryAdapter.java:83)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetProviderToFactoryAdapter.getDisplayName(StatusBarWidgetProviderToFactoryAdapter.java:41)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetProviderToFactoryAdapter.isConfigurable(StatusBarWidgetProviderToFactoryAdapter.java:67)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsOptionProvider.consumeTopHits(StatusBarWidgetsOptionProvider.java:32)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processTopHits(GotoActionItemProvider.java:141)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:95)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:99)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

gz#9132

**Comment by fcFn** [comment]
This is getting pretty annoying. Can I opt out of them?
