### ISSUE TITLE
Not working for me on PHPstorm

### ISSUE THREAD

**Issue by apedicdev** [codota/tabnine-intellij#304]
Hi, 

I've been trying to use it without success, even trying to use a fresh phpstorm version, as soon as I click settings I got the following errors:

```
Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:69)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:44)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:22)
	at com.tabnine.lifecycle.BinaryStateService.updateState(BinaryStateService.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:226)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

gz#13620

**Comment by Tabnineteam** [comment]
<i>(related to <a href='https:///agent/tickets/13620'>Zendesk ticket #13620</a>)</i>

**Comment by maya-tabnine** [comment]
Can you check the path /Users/{username}/.tabnine/ and tell me the latest version you have there?
 
Also, would try to uninstall Tabnine?
Try removing the files at:
/Users/{UserName}/Library/Preferences/TabNine
/Users/{UserName}/.tabnine
/Users/{UserName}//Library/Application Support/TabNine
 
And finally, reinstall Tabnine on PHPStorm.
Would you let me know if that works?

**Comment by maya-tabnine** [comment]
Hi if you still need our help, please ping us here or email support@tabnine.com

**Comment by maya-tabnine** [comment]
Hi if you still need our help, please ping us here or email [support@tabnine.com](mailto:support@tabnine.com)
