### ISSUE TITLE
Open Idea error

### ISSUE THREAD

**Issue by lujianzhao** [codota/tabnine-intellij#355]
idea version:IntelliJ IDEA 2022.1
tabnine version: 0.7.13

Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.NullPointerException
    at com.tabnine.state.UserState.<init>(UserState.java:27)
    at com.tabnine.state.UserState.init(UserState.java:15)
    at com.tabnine.Initializer.initialize(Initializer.java:47)
    at com.tabnine.Initializer.preload(Initializer.java:27)
    at com.intellij.idea.ApplicationLoader$executePreloadActivity$1.run(ApplicationLoader.kt:512)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.idea.ApplicationLoader.executePreloadActivity(ApplicationLoader.kt:502)
    at com.intellij.idea.ApplicationLoader.access$executePreloadActivity(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$executePreloadActivities$2.run(ApplicationLoader.kt:567)
    at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
    at com.intellij.idea.StartupUtil.start(StartupUtil.java:270)
    at com.intellij.idea.Main.bootstrap(Main.java:118)
    at com.intellij.idea.Main.main(Main.java:79)

-----
Your JRE: 11.0.15+10-b2043.56 x86_64 (JetBrains s.r.o.)
/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home

gz#16784

**Comment by maya-tabnine** [comment]
Hi! first, can you go to help > show log in finder/explorer and share what's on there? 
Then, would you try:
1. Uninstall Tabnine.
2. Remove all Tabnine files from the following paths:
the binary files (according to [Binary location by OS](https://support.tabnine.com/hc/en-us/sections/5232708641297-Binary-location-by-OS)) & [Models location](https://support.tabnine.com/hc/en-us/articles/5226305571089-Models-location) & [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
3. Reinstall Tabnine. Make sure you have the latest versions for the engine too (4.4.98). 

Also, what is your OS?

**Comment by lujianzhao** [comment]
@maya-tabnine 
macOS Catalina 10.15.7(19H1922)

**Comment by maya-tabnine** [comment]
@lujianzhao We released yesterday a new engine version 0.7.15.
Would you please check if you are now on the latest version or above? Do you still experience this problem?
