### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create class com.tabnineCommon.chat.ChatToolWindowListener

### ISSUE THREAD

**Issue by petr-nehez** [codota/tabnine-intellij#624]
Suddenly occurred...

```
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create class com.tabnineCommon.chat.ChatToolWindowListener (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Tabnine AI Code Completion- JS Java Python TS Rust Go PHP & More, id=com.tabnine.TabNine, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\231.8770.65.plugins\TabNine, version=1.0.42, package=null, isBundled=false), packagePrefix=null, instanceId=35, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:1072)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners$lambda$3(CompositeMessageBus.kt:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.kt:111)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers$intellij_platform_core(CompositeMessageBus.kt:92)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers$intellij_platform_core(MessageBusImpl.kt:210)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers$intellij_platform_core(CompositeMessageBus.kt:87)
	at com.intellij.util.messages.impl.MessagePublisher$publish$handlers$1.invoke(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher$publish$handlers$1.invoke(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher.publish$lambda$0(MessageBusImpl.kt:460)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:451)
	at jdk.proxy1/jdk.proxy1.$Proxy91.toolWindowShown(Unknown Source)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.fireToolWindowShown(ToolWindowManagerImpl.kt:1725)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:984)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:906)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1094)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1167)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at com.intellij.util.messages.impl.CompositeMessageBus.notifyOnSubscriptionToTopicToChildren$intellij_platform_core(CompositeMessageBus.kt:137)
	at com.intellij.util.messages.impl.MessageBusImpl.notifyOnSubscription$intellij_platform_core(MessageBusImpl.kt:231)
	at com.intellij.util.messages.impl.BaseBusConnection.subscribe(BaseBusConnection.kt:43)
	at com.tabnineCommon.chat.ChatToolWindowListener.<init>(ChatToolWindowListener.kt:20)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1017)
	... 65 more
```

```
IntelliJ IDEA 2023.1.1 (Ultimate Edition)
Build #IU-231.8770.65, built on April 27, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10504M
Cores: 12
Registry:
    debugger.click.disable.breakpoints=true
    editor.focus.mode.color.light=a2a2a2
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=a2a2a2
    editor.minimap.enabled=true
    majera.code.review.bitbucket.disable.gpu.in.jcef=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.intellij.javafx (1.0.4)
    org.dandoh.favacts (0.0.3)
    varme.pw.oceanic-dark-theme (1.1.6)
    Batch Scripts Support (1.0.13)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.macoskeymap (231.7515.9)
    org.turbanov.run.configuration.as.action (1.4.5)
    com.khmelyuk.multirun (1.13)
    lermitage.intellij.iconviewer (1.21.1)
    name.kropp.intellij.makefile (231.8109.91)
    com.layoutmanager (1.4.0)
    com.tabnine.TabNine (1.0.42)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    com.wakatime.intellij.plugin (14.1.4)
    PsiViewer (231-SNAPSHOT)
    ch.raffael.idea.plugins.runpopup (1.3.0)
    zielu.cleansheet (211.3.4)
    com.intellij.plugins.watcher (231.8109.91)
    org.rust.lang (0.4.194.5382-231)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.aqua.selenium (231.8109.91)
    com.intellij.ideolog (203.0.30.0)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.wix.sasslint (1.1.2)
    com.intellij.properties.bundle.editor (231.8109.91)
    Key Promoter X (2023.1.0)
    hunspell (231.8109.91)
    de.santiv.fastscrolling (1.2)
    com.github.today-.theme.spaceday (1.12)
    lermitage.intellij.extra.icons (2023.2.4-231)
    rasarts.espresso.light.theme (1.2.0)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    com.intellij.nativeDebug (231.8770.15)
    mobi.hsz.idea.gitignore (4.5.0)
    com.github.beansoftapp.visualgc.plugin (2022.1.0)
    com.jetbrains.jax.ws (231.8109.90)
    String Manipulation (9.7.1)
    CheckStyle-IDEA (5.79.0)
    com.intellij.javaee.ejb (231.8109.90)
    com.intellij.selenium (231.8109.91)
    com.intellij.aqua (231.8770.15)
    JFormDesigner-Marketplace-Edition (8.0.5)
    EclipseCodeFormatter (23.1.223.000.0-Eclipse_2023-03)
    com.github.setial (4.0.2)
    VisualVMLauncher (1.21.211.6085.0)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    org.mallowigi.idea.MaterialThemeUI.CustomTheme (2022.1.0)
    org.mallowigi.idea.MaterialThemeUI.LangAdditions (2022.1.1)
    org.mallowigi.idea.MaterialThemeUI.Extras (2022.1.1)
    com.intellij.bigdatatools (231.9011.1)
    izhangzhihao.rainbow.brackets (2023.2.7)
    com.haulmont.jpab (2023.2.2-231)
    GrepConsole (12.18.211.6693.0)
    pro.bashsupport (3.2.2.231)
    org.sonarlint.idea (8.2.0.68615)
    com.majera.intellij.codereview.bitbucket (2023.2.2.231)
    net.seesharpsoft.intellij.plugins.csv (3.2.0-231)
    com.mallowigi (90.0.0)
    zielu.gittoolbox (500.0.8+213)
    nix-idea (0.4.0.9)
    com.intellij.plugins.html.instantEditing (231.8770.15)

Kotlin: 231-1.8.21-IJ8770.65
```

gz#25950<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25950'>Zendesk ticket #25950</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @petr-nehez 
Make sure you have the latest version of Tabnine.
You can check it out [here](https://support.tabnine.com/hc/en-us/articles/5460798381201-Plugin-version).
