### ISSUE TITLE
Cannot use Tabnine Chat 

### ISSUE THREAD

**Issue by Stark-X** [codota/tabnine-intellij#627]
- Engine Version: 4.5.28-45
- Plugin Version: 1.0.48

I've already been selected to join the Tabnine Chat's beta, but I still cannot use the Tabnine Chat.

The "chat" popup stil display "Tabnine Chat is currently in Beta"

Here is an error I've found in the idea.log, it seems that the binary the "chat" required cannot be downlaod. What should I do now?

```
2023-08-25 11:22:14,200 [  48726]   WARN - #com.tabnineCommon.binary.BinaryProcessRequesterImpl - Binary returned illegal response: null
com.tabnineCommon.binary.exceptions.TabNineInvalidResponseException: Binary returned illegal response: null
        at com.tabnineCommon.binary.ParsedBinaryIO.readResponse(ParsedBinaryIO.java:33)
        at com.tabnineCommon.binary.BinaryProcessRequesterImpl.readResult(BinaryProcessRequesterImpl.java:63)
        at com.tabnineCommon.binary.BinaryProcessRequesterImpl.request(BinaryProcessRequesterImpl.java:42)
        at com.tabnineCommon.binary.BinaryRequestFacade.lambda$executeRequest$0(BinaryRequestFacade.java:36)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.tabnineCommon.binary.exceptions.TabNineInvalidResponseException: Binary returned null as a response
        at com.tabnineCommon.binary.ParsedBinaryIO.lambda$readResponse$0(ParsedBinaryIO.java:30)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at com.tabnineCommon.binary.ParsedBinaryIO.readResponse(ParsedBinaryIO.java:29)
        ... 11 more
```

gz#26039<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26039'>Zendesk ticket #26039</a>)</i>

**Comment by TzufTabnine** [comment]
@Stark-X 
Did you try to sign in (with the same email that you received access to the beta)? See more info about Tabnine Hub here:
https://support.tabnine.com/hc/en-us/articles/4413876147985-Tabnine-Hub-Where-to-find-it-and-how-to-sign-in.
What exactly doesn't work? Can you send us a screenshot/viedo of the issue?
Do you know if code completions work?

**Comment by Stark-X** [comment]
![image](https://github.com/codota/tabnine-intellij/assets/13653522/fb8bcb96-1dc6-4f92-9b8a-e950d8f62617)

I have already logged in.
The code suggestions are functioning properly, but the "chat" displayed the information as shown in the provided screenshot.
The only distinction between my account and the Tabnine account (shown on the Tabnine Hub) is that the "Tabnine Hub" displays the account with the first letter of each word in uppercase.

**Comment by TzufTabnine** [comment]
Did you try to sign in (**with the same email that you received access to the beta**)? If so, what is the email address?

**Comment by Stark-X** [comment]
yes, i've already used my subscribed account to signed in.
Here's my account `contact-me@stark-x.cn`. and the mail address displayed on Tabnine hub is `Contact-Me@Stark-X.Cn`

**Comment by TzufTabnine** [comment]
Please restart your IDE and check again.

**Comment by Stark-X** [comment]
It is currently functioning, thank you very much for your assistance.

By the way, is this an issue with the software or might it be due to an incorrect configuration?

**Comment by TzufTabnine** [comment]
Glad to hear that.
