### ISSUE TITLE
Webstorm 2023.2.2 exception in Tabnine Pro plugin

### ISSUE THREAD

**Issue by polo-git** [codota/tabnine-intellij#659]
The error occurs frequently, but seems to be irregular. This most often happens when rendering native Webstorm suggestions and simultaneous Tabnine "comment" suggestions underneath. 
Webstorm 2023.2.2, MacOS.

`com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action or Event Dispatch Thread (EDT) only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 55,4,main] 1597625300 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 271696318
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1038)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:421)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.findFileElement(SharedImplUtil.java:78)
	at com.intellij.psi.impl.source.SubstrateRef$2.isValid(SubstrateRef.java:66)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isValid(StubBasedPsiElementBase.java:253)
	at com.intellij.psi.impl.smartPointers.SmartPsiElementPointerImpl.getElement(SmartPsiElementPointerImpl.java:76)
	at com.intellij.psi.impl.source.tree.injected.ShredImpl.getHost(ShredImpl.java:163)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.lambda$isValid$2(DocumentWindowImpl.java:886)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:30)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.isValid(DocumentWindowImpl.java:876)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.getModificationStamp(DocumentWindowImpl.java:367)
	at com.intellij.psi.impl.source.tree.injected.DocumentWindowImpl.getText(DocumentWindowImpl.java:153)
	at com.intellij.openapi.editor.Document.getText(Document.java:48)
	at com.tabnineCommon.prediction.CompletionFacade.retrieveCompletions(CompletionFacade.java:89)
	at com.tabnineCommon.prediction.CompletionFacade.retrieveCompletions(CompletionFacade.java:64)
	at com.tabnineCommon.inline.InlineCompletionHandler.retrieveInlineCompletion(InlineCompletionHandler.java:225)
	at com.tabnineCommon.inline.InlineCompletionHandler.lambda$renderNewCompletions$5(InlineCompletionHandler.java:125)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)`

gz#27085<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27085'>Zendesk ticket #27085</a>)</i>

**Comment by TzufTabnine** [comment]
@polo-git 
Can you make sure you have the latest plugin (1.9.0)?

**Comment by polo-git** [comment]
Yup, 1.9.0
![image](https://github.com/codota/tabnine-intellij/assets/134446289/76a1ccb5-0ba5-41da-a035-9fd2b0ac8475)
