### ISSUE TITLE
hub stays as loading

### ISSUE THREAD

**Issue by pWoLiAn** [codota/tabnine-intellij#703]
![image](https://github.com/codota/tabnine-intellij/assets/49567139/2f63f041-ed18-4a6c-a716-cc398186236d)
GoLand 2023.3
Build #GO-233.11799.228, built on December 1, 2023
Licensed to Hewlett Packard Enterprise / joel scaria
Subscription is active until February 22, 2024.
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2008M
Cores: 8
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.properties (233.11799.172)
  com.redhat.devtools.intellij.telemetry (1.0.0.44)
  com.tabnine.TabNine (1.37.0)
  com.jetbrains.space (233.11799.165)
  com.intellij.ml.llm (233.11799.241)
  com.intellij.bigdatatools.core (233.11799.267)
  com.intellij.lang.jsgraphql (233.11799.172)
  org.jetbrains.plugins.docker.gateway (233.11799.244)

plugin version: 1.37.0

gz#28311<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/28311'>Zendesk ticket #28311</a>)</i>

**Comment by pWoLiAn** [comment]
2023-12-08 13:43:09,894 [  17291]   WARN - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Error starting TabNine.
com.tabnineCommon.binary.exceptions.NoValidBinaryToRunException
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.tabnineCommon.binary.fetch.BinaryVersionFetcher.fetchBinary(BinaryVersionFetcher.java:68)
	at com.tabnineCommon.binary.BinaryRun.generateRunCommand(BinaryRun.java:41)
	at com.tabnineCommon.binary.BinaryProcessRequesterProvider.lambda$initProcess$1(BinaryProcessRequesterProvider.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2023-12-08 13:43:11,027 [  18424]   WARN - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Tabnine is in invalid state, it is being restarted.
java.lang.RuntimeException: restartAttemptCounter: 2
Binary is dead
	at com.tabnineCommon.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:76)
	at com.tabnineCommon.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:49)
	at com.tabnineCommon.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:26)
	at com.tabnineCommon.lifecycle.BinaryStateService.updateState(BinaryStateService.java:27)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2023-12-08 13:43:11,064 [  18461]   INFO - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Can't get completions because Tabnine process is not started yet.

**Comment by TzufTabnine** [comment]
@pWoLiAn Please send us the full logs. See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.
Also, check [this ](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues)link
