### ISSUE TITLE
Exception in latest IDEA version

### ISSUE THREAD

**Issue by bottlerocketjonny** [codota/tabnine-intellij#725]
IntelliJ IDEA Ultimate: 2024.2.01
OS: Pop!_OS 22.04 LTS

```com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'FixCodeAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.tabnine.TabNine]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)```

gz#34278<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34278'>Zendesk ticket #34278</a>)</i>

**Comment by TzufTabnine** [comment]
Thanks @bottlerocketjonny . We are investigating the issue.

**Comment by TzufTabnine** [comment]
@bottlerocketjonny  Please update your plugin and let us know if it resolved the issue.
