### ISSUE TITLE
Error with Tabnine integration for IntelliJ on Fedora

### ISSUE THREAD

**Issue by danielk117-work** [codota/tabnine-intellij#738]
Hello,

I'm trying to use your IDE integration for IntelliJ PHPStorm on Fedora 41. 

PHPStorm was installed over the IntelliJ Toolbox. The Sidebar just whos the following empty toolbar.

![grafik](https://github.com/user-attachments/assets/91284181-dcb1-46bc-bd3a-6ad75a3aabf5)

I'm able to press the "Open Devtools" button and got the following empty window.

![grafik](https://github.com/user-attachments/assets/bf36bddc-7fe5-47de-8b5b-e774db6759db)

In the IDEA logs I've just found the following abnormal logline:

```
2024-12-11 08:26:30,164 [1086017]   WARN - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Tabnine is in invalid state, it is being restarted.
java.lang.RuntimeException: restartAttemptCounter: 1
Binary is dead
    at com.tabnineCommon.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:76)
    at com.tabnineCommon.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:54)
    at com.tabnineCommon.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:31)
    at com.tabnineCommon.lifecycle.BinaryStateService.updateState(BinaryStateService.java:27)
    at com.intellij.util.concurrency.Propagation$capturePropagationContext$$inlined$Runnable$1.run(Runnable.kt:17)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
    at java.base/java.lang.Thread.run(Thread.java:1583)
2024-12-11 08:26:30,168 [1086021]   INFO - #com.tabnineCommon.binary.fetch.BinaryVersionFetcher - found local bootstrapped version BinaryVersions{versionFullPath='/home/danielknapke/.tabnine/4.215.0/x86_64-unknown-linux-musl/TabNine', version='4.215.0'}
```

The code completition seems to work. I also see this toolbar inline the code.

![grafik](https://github.com/user-attachments/assets/5a72649a-7770-4ec3-98be-95a9252162e5)

But the chat is not working. PHPStorm is 2024.3.1 and plugin 1.173.0.

BTW, on the same system, the tabnine intergration for VS Code is working fine...

gz#37382<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37382'>Zendesk ticket #37382</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, can you please share the engine logs with us? https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-logs-on-JetBrains
Does it work without the IntelliJ Toolbox? Can you try to install Tabnine without it and see if it is working?

**Comment by danielk117-work** [comment]
The engine log: [tabnine_rCURRENT.log](https://github.com/user-attachments/files/18122253/tabnine_rCURRENT.log)

I've tried tabnine with a PHPStorm installed from flatpak. First it looks nearly the same, but...

![grafik](https://github.com/user-attachments/assets/666c4b35-2374-4f32-97e3-d80a1ff34b40)

When I disabled the sandbox for the "embedded browser" (https://youtrack.jetbrains.com/articles/JBR-A-11), it is running.

![grafik](https://github.com/user-attachments/assets/9f1393d9-76ad-42d0-b3b1-a6790d837923)

Seems to be no error with the tabnine intergration, as other "embedded browser" in my main PHPStorm are not working too (i.e. the preview of a markdown file). But my main PHPStorm is not showing this "embedded browser" button.

**Comment by danielk117-work** [comment]
Running `rm -rfv ~/.cache/JetBrains/PhpStorm2024.3/jcef_cache/Singleton*` before starting PHPStorm solved the error for me (credits to https://stackoverflow.com/questions/74523328/markdown-plugin-for-intellij-not-showing-preview/78698338#78698338).
