### ISSUE TITLE
BinaryCannotRecoverException

### ISSUE THREAD

**Issue by kermit-ye** [codota/tabnine-intellij#99]
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.allow.merge.buttons=false, ide.tooltip.initialDelay=595, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.tabnine.TabNine, de.netnexus.camelcaseplugin, io.github.qeesung.component.HighlightBracketPair, net.vektah.codeglance, mobi.hsz.idea.gitignore, izhangzhihao.rainbow.brackets, org.toml.lang, training, Docker, JettyRunner-GK, SequenceDiagram, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, com.codota.csp.intellij, MavenRunHelper, org.rust.lang

Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:58)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.lifecycle.BinaryNotificationsLifecycle$poll$1.run(BinaryNotificationsLifecycle.kt:24)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by boaz-codota** [comment]
Hey @kermit-ye thanks for reaching out!

Could you further explain how Tabnine behaves on your machine? Are you getting suggestion?

You are getting this error because Tabnine had crashed more than 5 consecutive times. Is is possible that your Antivirus is killing Tabnine's process? Is it possible that something else is blocking the process from starting?

Restarting your IDE will allow Tabnine to start again, tell me if it works (we would love to uncover the root cause to the issue, this is just so you could go back to coding with Tabnine suggestions).

**Comment by corsik** [comment]
After updating Tabnine, I also began to receive a similar error

```
PhpStorm 2020.3.2
Build #PS-203.7148.74, built on January 27, 2021
Subscription is active until November 22, 2021.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1969M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.github.jk1.ytplugin, com.tabnine.TabNine, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, intellij.prettierJS, ru.adelf.idea.dotenv
```

```
Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:58)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.lifecycle.BinaryStateService.updateState(BinaryStateService.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by corsik** [comment]
@boaz-codota will this problem be solved?

**Comment by kermit-ye** [comment]
> Hey @kermit-ye thanks for reaching out!
> 
> Could you further explain how Tabnine behaves on your machine? Are you getting suggestion?
> 
> You are getting this error because Tabnine had crashed more than 5 consecutive times. Is is possible that your Antivirus is killing Tabnine's process? Is it possible that something else is blocking the process from starting?
> 
> Restarting your IDE will allow Tabnine to start again, tell me if it works (we would love to uncover the root cause to the issue, this is just so you could go back to coding with Tabnine suggestions).

This happened after I updated
![image](https://user-images.githubusercontent.com/13169042/108936276-53980180-7689-11eb-9974-a21a2d29d9ad.png)
![image](https://user-images.githubusercontent.com/13169042/108936613-690d2b80-7689-11eb-894d-80a9ac8829b3.png)
![image](https://user-images.githubusercontent.com/13169042/108936966-80e4af80-7689-11eb-8e20-17aad4d63f93.png)

**Comment by cobysack1** [comment]
I'm having what seems to be the same problem. I have two error messages.
This came up first
![image](https://user-images.githubusercontent.com/26507481/109258509-56facc80-77f2-11eb-8f26-7886787dccda.png)
This appears a few moments later
![image](https://user-images.githubusercontent.com/26507481/109258550-6712ac00-77f2-11eb-822f-c51e39aeebdc.png)

There is also a 3rd error saying "Too many IDE fatal errors. Monitoring stopped."

**Comment by Dannyps** [comment]
I'm experiencing the same issue.

**Comment by ogrok** [comment]
Chiming in here to say I am also experiencing this issue. Exact same as screenshotted logs above. I am on M1 Mac mini working with "GoLand on Apple Silicon" binary. I had assumed that might be the reason for this issue but am now not so sure based on the above.

**Comment by avnerbarr** [comment]
@Dannyps @ogrok 
can you try to kill your IDE, make sure all TabNine process are stopped (kill them if they are zobies) and restart the IDE (it should restart the Tabnine process).
Let me know if it helps or still encountering issues

**Comment by ogrok** [comment]
It actually did resolve for me but only after a few times

**Comment by Dannyps** [comment]
@avnerbarr I don't know what transpired in the last few days, but the issue seems to have disappeared :|
Anyway, glad it works now. Thanks for the support.

**Comment by corsik** [comment]
I restored it to work with:
1. Deleted in PhpStorm
2. Deleted folder C\User\<UserName>\.tabnine
3. Install PhpStorm

**Comment by Red44** [comment]
I got the error by unplugging my mouse.

**Comment by ErickCodigo** [comment]
I am also presenting the same error :(

**Comment by toduyen** [comment]
hi everyone i found the simplest fix. My Tabnine is running fine.
Step 1: uninstall tabnine on WebStorm
Step 2: Delete file .tabnine at C/Users/Username
Step 3: Delete file TabNine at C/Users/Username/AppData/Roaming/TabNine 
Step 4: Open WebStorm install tabnine 


Good luck to you

**Comment by aiexz** [comment]
Fixed the problem on Mac by removing folder at` ~/.tabnine`

**Comment by rcoundon** [comment]
> ~/.tabnine

This just worked for me, too
